=pod

=head1 NAME

Solaris::Perf

=head1 VERSION

version 0.001

=head1 SYNOPSIS

    script/solaris_perf_server.pl

=head1 DESCRIPTION

[enter your description here]

=head1 NAME

Solaris::Perf - Catalyst based application

=head1 SEE ALSO

L<Solaris::Perf::Controller::Root>, L<Catalyst>

=head1 AUTHOR

Gordon Marler <gmarler@gmarler.com>

=head1 LICENSE

This library is free software. You can redistribute it and/or modify
it under the same terms as Perl itself.

=head1 AUTHOR

Gordon Marler <gmarler@gmarler.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2013 by Gordon Marler.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

