package Solaris::Perf::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Solaris::Perf::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=perfdb',
        user => 'catalyst',
        password => 'test',
        AutoCommit => q{1},
    }
);

=head1 NAME

Solaris::Perf::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Solaris::Perf>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Solaris::Perf::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Gordon Marler

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
