package Solaris::Perf::Web::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

# VERSION

my $dsn;
my $config_type = $ENV{CATALYST_CONFIG_LOCAL_SUFFIX};

if (defined($config_type) and ($config_type eq "dev")) {
  $dsn = "dbi:SQLite:share/solaris-perf-${config_type}.db";
} elsif (defined($config_type)) {
  die;
} else {
  $dsn = 'dbi:SQLite:share/solaris-perf.db';
}

__PACKAGE__->config(
    schema_class => 'Solaris::Perf::Schema',
    connect_info         => {
      dsn           => $dsn,
      user          => '',
      password      => '',
      on_connect_do => q{PRAGMA foreign_keys = ON;PRAGMA journal_mode=WAL;},
    },
);

=head1 NAME

Solaris::Perf::Web::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Solaris::Perf::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Solaris::Perf::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

Gordon Marler

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;

